# Generated by Django 5.0.2 on 2024-11-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership_team',
            name='link',
        ),
    ]
