# Generated by Django 5.0.2 on 2024-11-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_remove_leadership_team_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='leadership_team/')),
            ],
        ),
        migrations.AlterField(
            model_name='leadership_team',
            name='image',
            field=models.ImageField(upload_to='leadership_team/'),
        ),
    ]
