# Generated by Django 5.0.2 on 2024-11-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_testimonial_alter_leadership_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonial/'),
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.CharField(choices=[('A', 'All Student'), ('B', 'All Staff'), ('C', 'All Students and Staff'), ('D', 'Some Students')], default='A', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('time_range', models.CharField(max_length=100)),
                ('needed', models.CharField(default='All students', max_length=100)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadership.leadership_team')),
            ],
        ),
    ]
