# Generated by Django 5.0.2 on 2024-11-17 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_alter_testimonial_image_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='activities/'),
            preserve_default=False,
        ),
    ]
