# Generated by Django 5.0.2 on 2024-11-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_activities_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activities',
            name='assigned',
            field=models.CharField(choices=[('All Student', 'All Student'), ('All Staff', 'All Staff'), ('All Students and Staff', 'All Students and Staff'), ('Some Students', 'Some Students')], default='All Student', max_length=100),
        ),
    ]
