# Generated by Django 5.0.2 on 2024-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0007_remove_activities_supervisor_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='announcements/')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
