# Generated by Django 5.0.2 on 2024-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
