# Generated by Django 5.0.2 on 2024-11-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leadership', '0007_remove_activities_supervisor_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='testimonial/')),
            ],
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.CharField(choices=[('All Student', 'All Student'), ('All Staff', 'All Staff'), ('All Students and Staff', 'All Students and Staff'), ('Some Students', 'Some Students')], default='All Student', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('time_range', models.CharField(max_length=100)),
                ('needed', models.CharField(default='All students', max_length=100)),
                ('image', models.ImageField(upload_to='activities/')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadership.leadership_team')),
            ],
        ),
    ]
